script:
- yarn test
- yarn dist
before_install:
- yarn add global parcel-bundler
language: node_js
node_js: "9"
env:
- NODE_ENV=TEST
git:
  depth: 3
cache: yarn
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master